### ISSUE TITLE
Get value of a statement

### ISSUE THREAD

**Issue by tlatoza** [tlatoza/SeeCodeRun#20]
Index the execution trace to get a value summarizing each value. For a given line, first determine the corresponding statement. The value then depends on the type of statement.

assignment statements: value of variable being assigned
conditional statements: true or false
loops: total number of times loop executed
function invocations: return value of function

**Comment by luminaxster** [comment]
#39 presents this feature

**Comment by htsungwing** [comment]
David, thanks for helping me with implementing this functionality.

**Comment by htsungwing** [comment]
David brought up a good point that we should have the code tested before closing this issue!

**Comment by luminaxster** [comment]
Han, I realized that assignee is unique. Sorry about that, I thought I could be added to it, not replace you

**Comment by dana007** [comment]
I read my notes I took in the class on 2/2/16. Prof LaToza told us to list anyone who contributed since an issue can be assigned to only one person. 

I think from now on we need to remember that.

**Comment by htsungwing** [comment]
Sorry for misunderstanding your intention David. I appreciate you clearing out confusion~ I think for our feature team is more unique than the other teams since all the logic are essentially linked together. Once we finished this issue we should definitely make a pull request specifying this issue as a "team contribution" :)

**Comment by klein2ms** [comment]
I believe this is implemented given the state of the current gutter
