### ISSUE TITLE
Fix the router bug.

### ISSUE THREAD

**Issue by Alaboudi1** [tlatoza/SeeCodeRun#67]
Creating a new pastebine causes the page to freeze. There is a corrupted pastebin's data that is retrieved every time a new pastebine is accessed for the first time. It seems that refreshing the page fixes the issue.  Please see this [screencast ](http://screencast-o-matic.com/watch/cDe00O1T73)that shows the bug in action 
 .

**Comment by jbhilton11** [comment]
Seems as though I found the issue. I think we actually solved the corrupted pastebin part, however, there's a second portion to it. When the page starts to load, it gets a firebase key (assuming params.id is null/undefined) and then calls the router to navigate to the main page again, but this time passing the firebase key as the params.id. Then, it seems as though the attached() method(s) is/are called right before it gets back to the activate() method of the pastebin. This causes an issue because in each of the editors, we create a Firepad. This becomes problematic because it takes a baseUrl and concatenates it with a pastebinId that hasn't been passed in yet. The pastebinId gets passed in within the activate() method in the pastebin after it determines it has a pastebinId to pass along. This results in the infamous "undefined" firebase tree branch we've seen before. We may need to rethink how we can try to prevent this from happening before the routing happens.

**Comment by jbhilton11** [comment]
This would also make sense why the undefined firebase branch became so large...because each pastebin created would result in adding on to the "undefined" firebase branch.

**Comment by jbhilton11** [comment]
A possible solution could be to pass the pastebinId in the attached method instead of the activate method.

**Comment by Alaboudi1** [comment]
Is there a function call for reloading the page . So, instead of manually reloading it, just let the code does it for us :). I know it is not a good fix, but theoretically, this should work.

**Comment by jbhilton11** [comment]
That's what router.navigate() is doing, actually.  It seems that the code I have fixes it.  I'll create a bug branch and create a pull request to master.  Then master should be solid again, before merging in the changes you fixed in your pull request.

**Comment by Alaboudi1** [comment]
I have not tested the code in master branch yet, but last time I checked( one week ago), it was not working. If that is the case now, I would prefer you go and fix the issue in Abdulaziz branch, and then do the merge into master. Just a suggestion!
